// Demo recipes for Home and other components
import { Recipe } from "./types/Recipe";
import applePie from "./assets/apple-pie.jpg";
import bbqPulledPork from "./assets/bbq-pulled-pork.jpg";
import capreseSalad from "./assets/caprese-salad.jpg";
import chocolateLavaCake from "./assets/chocolate-lava-cake.jpg";
import grilledSalmon from "./assets/grilled-salmon.jpg";
import mushroomRisotto from "./assets/mushroom-risotto.jpg";
import pastaCarbonara from "./assets/pasta-carbonara.jpg";
import thaiGreenCurry from "./assets/thai-green-curry.jpg";

export const demoRecipes: Recipe[] = [
  {
    id: "demo-1",
    title: "Apple Pie",
    description: "Classic apple pie with cinnamon.",
    image: applePie,
    cookTime: "1h",
    servings: 8,
    difficulty: "Medium" as const,
    category: "Dessert",
    ingredients: [
      "6 cups thinly sliced apples",
      "3/4 cup sugar",
      "2 tablespoons flour",
      "1/2 teaspoon cinnamon",
      "1/4 teaspoon salt",
      "2 tablespoons butter",
      "2 pie crusts",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C)",
      "Mix apples, sugar, flour, cinnamon, and salt in large bowl",
      "Place bottom crust in 9-inch pie pan",
      "Fill with apple mixture and dot with butter",
      "Cover with top crust and seal edges",
      "Cut slits in top crust for steam vents",
      "Bake 40-50 minutes until golden brown",
    ],
    tags: ["dessert", "apple", "traditional", "baking"],
    createdBy: "demo",
  },
  {
    id: "demo-2",
    title: "BBQ Pulled Pork",
    description: "Slow-cooked pork with BBQ sauce.",
    image: bbqPulledPork,
    cookTime: "6h",
    servings: 6,
    difficulty: "Hard" as const,
    category: "Main",
    ingredients: [
      "3-4 lb pork shoulder",
      "2 tablespoons brown sugar",
      "1 tablespoon paprika",
      "2 teaspoons garlic powder",
      "2 teaspoons onion powder",
      "1 teaspoon cayenne pepper",
      "1 cup BBQ sauce",
      "1/2 cup apple cider vinegar",
    ],
    instructions: [
      "Mix all dry ingredients to create rub",
      "Rub mixture all over pork shoulder",
      "Place in slow cooker with apple cider vinegar",
      "Cook on low for 6-8 hours until tender",
      "Remove pork and shred with two forks",
      "Mix with BBQ sauce",
      "Serve on buns with coleslaw",
    ],
    tags: ["bbq", "pork", "slow-cooked", "main-course"],
    createdBy: "demo",
  },
  {
    id: "demo-3",
    title: "Caprese Salad",
    description: "Fresh mozzarella, tomatoes, basil.",
    image: capreseSalad,
    cookTime: "10m",
    servings: 2,
    difficulty: "Easy" as const,
    category: "Salad",
    createdBy: "demo",
  },
  {
    id: "demo-4",
    title: "Chocolate Lava Cake",
    description: "Rich chocolate cake with molten center.",
    image: chocolateLavaCake,
    cookTime: "30m",
    servings: 4,
    difficulty: "Medium" as const,
    category: "Dessert",
    createdBy: "demo",
  },
  {
    id: "demo-5",
    title: "Grilled Salmon",
    description: "Salmon fillet grilled to perfection.",
    image: grilledSalmon,
    cookTime: "20m",
    servings: 2,
    difficulty: "Easy" as const,
    category: "Main",
    createdBy: "demo",
  },
  {
    id: "demo-6",
    title: "Mushroom Risotto",
    description: "Creamy risotto with mushrooms.",
    image: mushroomRisotto,
    cookTime: "45m",
    servings: 4,
    difficulty: "Medium" as const,
    category: "Main",
    createdBy: "demo",
  },
  {
    id: "demo-7",
    title: "Pasta Carbonara",
    description: "Classic Italian pasta with pancetta.",
    image: pastaCarbonara,
    cookTime: "25m",
    servings: 2,
    difficulty: "Easy" as const,
    category: "Main",
    createdBy: "demo",
  },
  {
    id: "demo-8",
    title: "Thai Green Curry",
    description: "Spicy green curry with chicken.",
    image: thaiGreenCurry,
    cookTime: "40m",
    servings: 4,
    difficulty: "Medium" as const,
    category: "Main",
    createdBy: "demo",
  },
];
// TODO: merge demo with backend data where relevant
